# Generated by Django 5.2.4 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudevent',
            name='authenticated_user_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='crudevent',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
